### ISSUE TITLE
Feature Request:  When locking by label, return randomly selected item(s)

### ISSUE THREAD

**Issue by troy-rudolph** [jenkinsci/lockable-resources-plugin#160]
We are using this feature in Jenkins to select which server to run our webapp on.  We would like to randomly choose one to spread the work around better.

One very simple way to do this would be to modify LockableResourcesManager::getResourcesWithLabel() to do the following.

return java.util.Collections.shuffle(found);

Thoughts?

Thank you

**Comment by TobiX** [comment]
That sounds useful, but I would prefer to make it configurable. I wonder if some presets (FIRST, RANDOM, other useful strategies) are enough or if it would be useful to allow custom code (as was thinking of closures in pipeline) without opening another can of worms... Probably start with some presets first and keep the current behaviour as default.

**Comment by famod** [comment]
This might be a bit beyond the scope of this request but one strategy/preset could be `PRIORITY` in combination with being able to assign a priority value to a resource.

**Comment by denhamcoote** [comment]
Another vote for this request, please.  I have a pool of servers I deploy & test to, and don't particularly care which is used, so a 'random' preset would be great.

**Comment by robythomas** [comment]
We've a particular case where we want the least recently used item to be allocated. At-least, a random item is the next better alternative. This is because we need to perform some clean-up on the used pool of servers. This cleanup is not mandatory after every workload use, but occasionally some left over from the prior job can cause trouble. So we've two sets of job, one which primarily uses this pool of server as workload. The other is the one which cycles through the pool explicitly and cleans it up. Our problem is that the primary job which relies on label keeps using the first item, when there aren't any contenders.

**Comment by mPokornyETM** [comment]
see #215
