### ISSUE TITLE
Please incorporate existing features into Freestyle jobs

### ISSUE THREAD

**Issue by rnickle79** [jenkinsci/lockable-resources-plugin#221]
Hi,

I noticed using lockable resources in freestyle jobs is really limited compared to what you can do with a pipeline job. 

e.g.,
    1.  You only get one variable for storing locked resources
    2.  You can really only lock based on one label.... unless you use a groovy expression... but still you only get one variable.

However, with a pipeline job you can lock on multiple labels with unique variables.

e.g.,
```
node {
    stage("Lock Test") {
        lock(label: 'SERVER', quantity: 1, variable: 'MY_SERVER') {
            lock(label: 'CLIENT', quantity: 1, variable: 'MY_CLIENT') {
                lock(label: 'OTHER', quantity: 1, variable: 'MY_OTHER') {
                    echo "Test"
                    echo "Server Locked: ${env.MY_SERVER}"
                    echo "Client Locked: ${env.MY_CLIENT}"
                    echo "Other Locked: ${env.MY_OTHER}"
                }    
            }
        }
    }
}
```
It would be great if we could get this kind of functionality in freestyle jobs.

**Comment by TobiX** [comment]
I won't work on this myself, since I basically stopped using Freestyle jobs - Clean pull requests with good test coverage is always welcome, though.

**Comment by mPokornyETM** [comment]
Probably nobody will implement it. Or better to say in last 2 years has nobody change everything in this direction. I checked the implementation for free style projects an my conclusion us. Do not use it  😁. It is done in difficult way (of course, because of Jenkins architecture) and it will be very hard to merge it with pipeline functionalities. Just one example. The queue mechanism works absolute other compare to pipeline. It is also not possible to show it in the queue page.
Therefore I will close this issue now without any change. Sorry for that.
