### ISSUE TITLE
[documentation] show example with Declarative syntax

### ISSUE THREAD

**Issue by erlangparasu** [jenkinsci/lockable-resources-plugin#322]
### Describe your use-case which is not covered by existing documentation.

please show example with Declarative syntax

**Comment by Jagrutiti** [comment]
Hey,

Could you tell me which examples should be shown with Declarative syntax?  Do you speak of the ones in `read.me` file?

**Comment by MarkEWaite** [comment]
> Could you tell me which examples should be shown with Declarative syntax? Do you speak of the ones in `readme.md` file?

Those examples are a good place to start.

**Comment by Jagrutiti** [comment]
Hey @mPokornyETM 

In the Gitter channel you mentioned:

>I think there is a test for declarative pipeline. So you can grab the test code and bring it in readme file as well 

Can I get a document or something more to understand and start with the declarative pipeline?  And how to bring the code in `readme` file?

**Comment by mPokornyETM** [comment]
@Jagrutiti  Welcome to open-source hell (or heaven ;-) ) Our fist step is done. You has contact community as well.

## For contributing you shall

  + Create new fork from this repository.
  + read this document. https://github.com/jenkinsci/lockable-resources-plugin/blob/master/CONTRIBUTING.md It is easy and short. Shall works as described ( i have test it at the creation time) When there are some missing information or is something wrong raise a new issue here in github (in best case PR with changes).

## General info about documentation in this plugin

+ I starts with some documentation issues, see #401 . 
+ The documentation shall be structured and easy to read. Something like this https://github.com/jenkinsci/lockable-resources-plugin/pull/401/commits/bae2a94091bed0de47fc7c99a3ae3badcae354fd
+ All currently open issues to documentation are labelled and you can find it here
https://github.com/jenkinsci/lockable-resources-plugin/labels/documentation

## And about the syntax.

When you follow contributing document, you will have own local jenkins instance. That great place to play with jenkins. Look also here https://www.jenkins.io/doc/book/pipeline/syntax/ or better here https://www.jenkins.io/doc/book/pipeline/getting-started/ It is great tutorial (many thanks to @MarkEWaite and the team)

note. Please look in other open documentation issues. There are many examples also for scripted pipeline. Link all of them with this issues. Then try to execute the example (just be sure it works).

note:
To eliminate merge conflicts, i will create new branch `extend-documentation` in the plugin workspace and merge my changes there. After them you can create our own branch (in your forked repository) and commit there anything you want. Then you need to create PR in to extend-documentation. We will close all issues by merge the `extend-documentation` in to `master`
I hope this scenario is fine for you. Please get me feedback, otherwise I will continue only in my branch as well.
Thx
After them you need add this example in the /doc/examples struct.

**Comment by Jagrutiti** [comment]
Hey @mPokornyETM 

Thank you so much for your detailed reply. 

I laughed out loud when I read:

>Welcome to open-source hell (or heaven ;-) )

I feel you. 

I think there are a lot of issues in the documentation that will keep me engaged. 

Your instructions are clear. Here is the gist of what I have understood.

1) Follow `CONTRIBUTING.md` to set up the plugin locally.
2) One by one pick the open issues to resolve. Not before noting the syntax that is followed in documentation.

The idea of `extend-documentation` branch sounds good to me. Merge conflicts can result in open-source hell. We don't want that.

**Comment by mPokornyETM** [comment]
Great 👍.  Let me merge my changes. Probably today or tomorrow. Then you can start.

One more question.  In which area you want contribute?  Documentation.  Java coding. Testing. Ui design. Or localisation (any new language will be fine)

**Comment by mPokornyETM** [comment]
The branch is created https://github.com/jenkinsci/lockable-resources-plugin/tree/extend-documentation and my changes are merge https://github.com/jenkinsci/lockable-resources-plugin/pull/401. You can continue now. When you has some changes pls address the PR to me. I will stop now for this topic. There are also many other points to do ;-)

**Comment by mPokornyETM** [comment]
related to #44 #56 #58

**Comment by Jagrutiti** [comment]
Hey @mPokornyETM 

I will contribute to either Documentation, Java coding, or testing. I am not good at UI or localization (maybe I can do this not sure though)

Could you tell which contribution would help this plugin the most from Documentation, Java coding, and testing?

I would like to contribute to the code area more. Because to learn documentation I am already contributing to other repos. 

I am good with either. Whatever helps this repository the most.

**Comment by mPokornyETM** [comment]
> Could you tell which contribution would help this plugin the most from Documentation, Java coding, and testing?

Can we switch pls this discussions here ? https://gitter.im/jenkinsci/lockable-resources

**Comment by mPokornyETM** [comment]
@Jagrutiti  Can you pls create an entry in readme.md about this? The question comes often ;-)

_Originally posted by @mPokornyETM in https://github.com/jenkinsci/lockable-resources-plugin/issues/275#issuecomment-1321598734_

**Comment by Jagrutiti** [comment]
> @Jagrutiti Can you pls create an entry in readme.md about this? The question comes often ;-)


Done
