### ISSUE TITLE
Add help text for "steal lock" button

### ISSUE THREAD

**Issue by cccCody** [jenkinsci/lockable-resources-plugin#323]
### Describe your use-case which is not covered by existing documentation.

Consider adding documentation or help text for the "steal lock" button. As a user of this plugin, it's unclear to me what that will actually do. What will happen to a build that's currently executing if I steal its lock? Will the job/stage/step be terminated? I don't see anything about stealing mentioned in the readme or on the plugin's info page.

**Comment by mPokornyETM** [comment]
Gret I issue, I tries to use DataTable in the plugin (enable filtering and other great features) and I found, that there are many actions which you newer see (because of logic issue in jelly code). Here is full list.
Unlock
Steal lock
Reserve
Unreserve
Reassign
Reset

I try to update the documentation in my branch, when I am finish

**Comment by mPokornyETM** [comment]
The action buttons contains tooltip text, which explains what the action does.
Therefore partly implemented by #365 .
Documentation shall be updated.
